# NOTE: update this with your service name
service: notes-app-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}
    tableName: notes
    
  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn.aws:dynamodb:us-east-1:038479334420:table/notes"

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /notes
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
  create:
    handler: functions/create.main
    events:
      - http:
          path: notes
          method: post
          corst: true
          authorizer: aws_iam
  
  get:
    handler: functions/get.main
    events:
      - http:
        path: notes/{id}
        method: get
        cors: true
        authorizer: aws_iam

  list:
    handler: functions/list.main
    events:
      - http:
        path: notes
        method: get
        cors: true
        authotizer: aws_iam

